In [3]:
import numpy as np

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
np.__version__

'1.26.4'

In [6]:
__author__ = 'kyubyong. longinglove@nate.com'

In [7]:
np.random.rand(3, 2) 
# Or np.random.random((3,2))

array([[0.07370862, 0.62296633],
       [0.0876213 , 0.63242718],
       [0.05375028, 0.35003142]])

In [12]:
out1 = np.random.randn(1000, 1000)
out2 = np.random.standard_normal((1000, 1000))
out3 = np.random.normal(loc=0.0, scale=1.0, size=(1000, 1000))
assert np.allclose(np.mean(out1), np.mean(out2), atol=0.1)
assert np.allclose(np.mean(out1), np.mean(out3), atol=0.1)
assert np.allclose(np.std(out1), np.std(out2), atol=0.1)
assert np.allclose(np.std(out1), np.std(out3), atol=0.1)
print (np.mean(out3))
print (np.std(out1))

0.0009227349846458201
1.0006950771146


In [13]:
np.random.randint(0, 4, (3, 2))

array([[2, 2],
       [2, 3],
       [0, 3]])

In [14]:
x = [1,2]
y = [[4, 1], [2, 2]]
#print np.dot(x, y)
#print np.dot(y, x)
#print np.matmul(x, y)
#print np.inner(x, y)
#print np.inner(y, x)

In [16]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
L = np.linalg.cholesky(x)
print (L)
assert np.array_equal(np.dot(L, L.T.conjugate()), x)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [20]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print("q=\n", q, "\nr=\n", r)
assert np.allclose(np.dot(q, r), x)

q=
 [[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
 [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]
